#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  This file is part of solus-sc
#
#  Copyright © 2017 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#

from plugins.snapd import SnapdPlugin
from plugins import ProviderStorage, PopulationFilter, ItemStatus
from plugins.native import get_native_plugin

class DummyStorage(ProviderStorage):

    skip_devel = None

    def __init__(self):
        self.skip_devel = True

    def add_item(self, id, item):
        if self.skip_devel and item.has_status(ItemStatus.META_DEVEL):
            return
        print("New item! {} - {} ({})".format(item.get_title(), id, item.get_version()))


    def clear(self):
        pass


def snapdDemo():
    store = DummyStorage()
    plugins = [
        SnapdPlugin(),
    ]

    osPlugin = get_native_plugin()
    if osPlugin is not None:
        plugins.insert(0, osPlugin)
    else:
        print("WARNING: Unsupported OS, native package management unavailable!")

    # Ask all plugins to populate with installed filter
    popfilter = PopulationFilter.INSTALLED
    for p in plugins:
        p.populate_storage(store, popfilter, None)

    # We want to be able to stop a search ...
    searchStore = DummyStorage()
    term = "vlc"
    print(" -> searching for %s" % term)
    for p in plugins:
        p.populate_storage(store, PopulationFilter.SEARCH, term)

    sources = [x for y in plugins for x in y.sources()]
    for x in sources:
        print(" -> Source: {}".format(x.describe()))

if __name__ == "__main__":
    snapdDemo()
