#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  This file is part of solus-sc
#
#  Copyright © 2017 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#

import gi
gi.require_version('Snapd', '1')
from gi.repository import Snapd
import sys

def snapdDemo():
    cl = Snapd.Client()
    cl.connect_sync()
    snaps = cl.list_sync()
    for snap in snaps:
        print("%s - %s (%s)" % (snap.get_name(), snap.get_title(), snap.get_version()))
        print(" -> tracking channel: %s" % snap.get_tracking_channel())


if __name__ == "__main__":
    snapdDemo()
